name: main

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2.1.0
    - name: Set up JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8
    - name: Run check
      run: ./gradlew check
    - name: Run JaCoCo
      run: ./gradlew jacocoTestReport
    - name: Codecov
      uses: codecov/codecov-action@v1.0.6
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
